---
title: "Exploratory Data Analysis"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r}
library(tidyverse)
library(ggplot2)
library(ggmap)
library(dplyr)
```


```{r}



ld1 <- read.csv("C:\\Users\\dange\\Documents\\pandemic_lockdown_sentiment_analysis\\datasets_csv\\processed_1\\lockdown1.csv")
ld2 <- read.csv("C:\\Users\\dange\\Documents\\pandemic_lockdown_sentiment_analysis\\datasets_csv\\processed_1\\lockdown2.csv")
ld3 <- read.csv("C:\\Users\\dange\\Documents\\pandemic_lockdown_sentiment_analysis\\datasets_csv\\processed_1\\lockdown3.csv")
ld4 <- read.csv("C:\\Users\\dange\\Documents\\pandemic_lockdown_sentiment_analysis\\datasets_csv\\processed_1\\lockdown4.csv")

ld1['lockdown'] <- "1.0"
ld2['lockdown'] <- "2.0"
ld3['lockdown'] <- "3.0"
ld4['lockdown'] <- "4.0"

ld1 <- drop_na(ld1)
ld2 <- drop_na(ld2)
ld3 <- drop_na(ld3)
ld4 <- drop_na(ld4)

ld1$time <- as.POSIXct(ld1$time, format="%a %b %d %H:%M:%S +0000 %Y")
ld2$time <- as.POSIXct(ld2$time, format="%a %b %d %H:%M:%S +0000 %Y")
ld3$time <- as.POSIXct(ld3$time, format="%a %b %d %H:%M:%S +0000 %Y")
ld4$time <- as.POSIXct(ld4$time, format="%a %b %d %H:%M:%S +0000 %Y")

ld <- rbind(ld1, ld2, ld3, ld4)

```


```{r}

ggplot(data=ld1, aes(x=time, y=sentiment_score)) + geom_line() + ggtitle("Lockdown 1.0")

ggplot(data=ld2, aes(x=time, y=sentiment_score)) + geom_line() + ggtitle("Lockdown 2.0")

ggplot(data=ld3, aes(x=time, y=sentiment_score)) + geom_line() + ggtitle("Lockdown 3.0")

ggplot(data=ld4, aes(x=time, y=sentiment_score)) + geom_line() + ggtitle("Lockdown 4.0")

ggplot(data=ld, aes(x=time, y=sentiment_score)) + geom_line() + ggtitle("Lockdown 1.0-4.0")

```
```{r}
hist(ld$sentiment_score)
```


```{r}
analyse_lockdown <- function(data){
  
  bbox = c(left=68.1766451354, bottom=7.96553477623, right=97.4025614766, top=35.4940095078)
  get_stamenmap(bbox = bbox, zoom = 6, maptype = "terrain-lines") %>%
    ggmap() + geom_point(data=data, aes(x=longitude, y=latitude, color=sentiment_score), size=1) + 
                      ggtitle(data$lockdown[0]) + 
            scale_colour_gradient2( low = "red", mid = "#eaebea", high = "blue", space = "Lab" , guide = "colourbar", aesthetics = "colour")
}


```


```{r}
analyse_lockdown(ld1)
analyse_lockdown(ld2)
analyse_lockdown(ld3)
analyse_lockdown(ld4)
analyse_lockdown(ld)
```
```{r}
sentiment_analysis <- as.data.frame(matrix(c(
  c(lockdown="1.0", negative=round(100*(length(ld1$sentiment_score[ld1$sentiment_score<0])/length(ld1$sentiment_score)), digits=2),
                    neutral=round(100*(length(ld1$sentiment_score[ld1$sentiment_score==0])/length(ld1$sentiment_score)), digits=2),
                    positive=round(100*(length(ld1$sentiment_score[ld1$sentiment_score>0])/length(ld1$sentiment_score)), digits=2)),
  
  c(lockdown="2.0", negative=round(100*(length(ld2$sentiment_score[ld2$sentiment_score<0])/length(ld2$sentiment_score)), digits=2),
                    neutral=round(100*(length(ld2$sentiment_score[ld2$sentiment_score==0])/length(ld2$sentiment_score)), digits=2),
                    positive=round(100*(length(ld2$sentiment_score[ld2$sentiment_score>0])/length(ld2$sentiment_score)), digits=2)),
  
  c(lockdown="3.0", negative=round(100*(length(ld3$sentiment_score[ld3$sentiment_score<0])/length(ld3$sentiment_score)), digits=2),
                    neutral=round(100*(length(ld3$sentiment_score[ld3$sentiment_score==0])/length(ld3$sentiment_score)), digits=2),
                    positive=round(100*(length(ld3$sentiment_score[ld3$sentiment_score>0])/length(ld3$sentiment_score)), digits=2)),
  
  c(lockdown="4.0", negative=round(100*(length(ld4$sentiment_score[ld4$sentiment_score<0])/length(ld4$sentiment_score)), digits=2),
                    neutral=round(100*(length(ld4$sentiment_score[ld4$sentiment_score==0])/length(ld4$sentiment_score)), digits=2),
                    positive=round(100*(length(ld4$sentiment_score[ld4$sentiment_score>0])/length(ld4$sentiment_score)), digits=2))
), byrow = TRUE, ncol = 4, nrow=4, dimnames=c(list(c(1,2,3,4), c("lockdown", "negative", "neutral", "positive")))))

sentiment_analysis
```
```{r}
ggplot(data=ld, aes(x=latitude, y=sentiment_score)) + geom_point() + 
                    ggtitle(paste("Sentiment Score V/S Latitude\npearson's r = ", cor(ld$latitude, ld$sentiment_score, method="pearson")))

ggplot(data=ld, aes(x=longitude, y=sentiment_score)) + geom_point() + 
                    ggtitle(paste("Sentiment Score V/S Longitude\npearson's r = ", cor(ld$longitude, ld$sentiment_score, method="pearson")))
```

